apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blossom-ingress
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          # Users API
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: users-service
                port:
                  number: 80
          # Cards API
          - path: /carts
            pathType: Prefix
            backend:
              service:
                name: carts-service
                port:
                  number: 80
          # Orders API
          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: orders-service
                port:
                  number: 80
          # Products API
          - path: /products
            pathType: Prefix
            backend:
              service:
                name: products-service
                port:
                  number: 80
          # Payments API
          - path: /payments
            pathType: Prefix
            backend:
              service:
                name: payments-service
                port:
                  number: 80
          
          - - path: /cards
              pathType: Prefix
              backend:
               service:
                name: payments-service
                port:
                  number: 80
